import = [
  "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

working_directory = "None"
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "None"
option_as_alt = "OnlyLeft"

[font]
size = 16
normal = { family = "Iosevka Term", style = "Regular" }
bold = { family = "Iosevka Term", style = "Bold" }
italic = { family = "Iosevka Term", style = "Italic" }

[cursor]
style = { shape = "Beam", blinking = "On" }
