[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x10/home/irvingwash)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x37\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x37\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x37)

[FullScreen]
pos=@Point(560 1016)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(936 939)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/irvingwash/Videos/Recordings/2023-10-02%2000-38-00.mkv, file:///home/irvingwash/Videos/Recordings/2023-10-02%2000-32-32.mkv, file:///home/irvingwash/Videos/Recordings/2023-09-27%2020-22-19.mkv, file:///home/irvingwash/Downloads/Telegram%20Desktop/Screen%20Recording%202023-08-29%20at%2019.58.08.mov, file:///home/irvingwash/Videos/Recordings/2023-08-29%2021-51-57.mkv, file:///home/irvingwash/Downloads/Telegram%20Desktop/lv_0_20230828210625.mp4, file:///home/irvingwash/Videos/Recordings/2023-08-28%2023-28-55.mkv, file:///home/irvingwash/Videos/Recordings/2023-08-27%2020-11-58.mkv, file:///home/irvingwash/Videos/Recordings/2023-07-12%2018-08-59.mkv, file:///home/irvingwash/Videos/Recordings/2023-05-27%2016-41-24.mkv, file:///home/irvingwash/2023-05-27%2016-39-40.mkv
times=0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
