format = """
[](#9A348E)\
$character\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$rust\
$odin\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

add_newline = false

[character]
success_symbol = "[ ⇊  ](bold white bg:#9A348E)"
error_symbol = "[ ⇊  ](bold red bg:#9A348E)"
vimcmd_symbol = "[ ⇅  ](bold white bg:#9A348E)"
vimcmd_replace_one_symbol = "[ ⇆  ](bold white bg:#9A348E)"
vimcmd_replace_symbol = "[ ⇆  ](bold white bg:#9A348E)"
vimcmd_visual_symbol = "[ ↹  ](bold white bg:#9A348E)"
format = "$symbol"

[username]
show_always = false
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = "[ $user ]($style)"
disabled = false

[os]
style = "bg:#9A348E"
disabled = true

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "../"

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ]($style)'

[odin]
symbol = "Ø"
style = "bg:#86BBD8"
format = '[ $symbol ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#33658A"
format = '[ $time ]($style)'
