local alpha = require('alpha');
local dashboard = require('alpha.themes.dashboard');

local logo = {
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMW#WMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMWW<hWMMWMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMM#cdMWO;'l#MMhwWMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMWM-pMMMW( xMMMMt/MMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMWX'LMMMMW(.rMMMMMvikMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMk>`0MWMMMW(.rMMMMMMf'n#MMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMM#v''cMMMMMMW) jMMMMMWM_':#&MMMMMMMMMMMMM",
	"MMMMMMMMMMMMMW0^.,LMWMMMMW) jMMMMMW*f..!kMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMWWt^.`dWMMMW1 jMMMMMZ'.>qMWMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMn''-WWMW) jMMMo>'iqWMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMWMW&j^^x#W1.jM*t.iZWMWMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMWM&/'.L1.fd.,qWWMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMWan.. ..Q*WMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMk}.. ..~kWMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMW-''[1'1v. >oMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMM{'.?aW( |#o}.'|#WMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMWMM*(..;wMMW| |MMWbl'.nMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMWM*1.'.cMMMMW| |#MMMMZ'.^Y#MWMMMMMMMMMMMM",
	"MMMMMMMMMMMMMWx..`jMWMMMMW| (MMMMMM#1. 'wMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMM#U` 'QMMMMMW| (MMMMW#{ .hhWMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMWW#Y'.,0WMMW| (MMW*n'.'0#MMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMM1'.;pWW|./#Mq;..n#MMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMW*]''lM( (W}'.fMWMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMo[//^., .aaMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMWMM~. .lpMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMa|w#WMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
}

dashboard.section.header.val = logo;

dashboard.section.buttons.val = {
		dashboard.button( 'e', '  > New file' , ':ene <BAR> startinsert <CR>'),
		dashboard.button( 'f', '  > Find file', ':cd $HOME/Documents | Telescope find_files<CR>'),
		dashboard.button( 'r', '  > Recent'	 , ':Telescope oldfiles<CR>'),
		dashboard.button( 's', '  > Settings' , ':e $MYVIMRC | :cd %:p:h | split . | wincmd k | pwd<CR>'),
		dashboard.button( 'q', '  > Quit', ':qa<CR>'),
}

alpha.setup(dashboard.opts);
