#!/usr/bin/env sh

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=bottom height=25 blur_radius=0 color=0xFF000000

default=(
    padding_left=5
    padding_right=5
    icon.font="Iosevka Nerd Font:Bold:17.0"
    label.font="Iosevka Nerd Font:Bold:14.0"
    icon.color=0xffffffff
    label.color=0xffffffff
    icon.padding_left=1
    icon.padding_right=1
    label.padding_left=1
    label.padding_right=1
)
sketchybar --default "${default[@]}"

# Spaces
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
    sid="$(($i+1))"
    space=(
        space="$sid"
        icon="${SPACE_ICONS[i]}"
        icon.padding_left=7
        icon.padding_right=7
        background.color=0x40ffffff
        background.corner_radius=5
        background.height=25
        label.drawing=off
        script="$PLUGIN_DIR/space.sh"
        click_script="yabai -m space --focus $sid"
    )
    sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

# Left items
sketchybar \
    --add item chevron left                                                \
        --set chevron icon=󰄾 label.drawing=off                             \
    --add item front_app left                                              \
        --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
        --subscribe front_app front_app_switched

# Right items
sketchybar \
    --add item keyboard right                                                      \
        --set keyboard                                                             \
            script="$PLUGIN_DIR/keyboard_layout.sh"                                \
        --add event keyboard_change "AppleSelectedInputSourcesChangedNotification" \
        --subscribe keyboard keyboard_change                                       \
    --add item  ip_address right                                                   \
        --set       ip_address script="$PLUGIN_DIR/ip_address.sh"                  \
            update_freq=30                                                         \
        --subscribe ip_address wifi_change                                         \
    --add item volume right                                                        \
        --set volume script="$PLUGIN_DIR/volume.sh"                                \
        --subscribe volume volume_change                                           \
    --add item battery right                                                       \
        --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh"              \
        --subscribe battery system_woke power_source_change                        \
    --add item clock right                                                         \
        --set clock icon=󰥔 update_freq=10                                          \
        label="$(date +'%H:%M')"                                                   \
    --add item calendar right                                                      \
        --set calendar icon= update_freq=1000                                     \
        label="$(date +'%a %d %b')"                                                \
    --add item slack right                                                         \
        --set slack                                                                \
            update_freq=60                                                         \
            script="$PLUGIN_DIR/slack.sh"                                          \
        --subscribe slack system_woke                                              \
    --add item telegram right                                                      \
        --set telegram                                                             \
            update_freq=60                                                         \
            script="$PLUGIN_DIR/telegram.sh"                                       \
        --subscribe telegram system_woke

sketchybar --update
