[manager]
show_hidden = true
show_symlink = true
linemode = "size_and_time"

[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix"}
]
play = [
    { run = 'vlc -f "$@"', block = true, for = "unix"}
]
