[mgr]
ratio          = [2, 3, 3]
show_hidden    = true
show_symlink   = true
sort_dir_first = true
scrolloff      = 10

[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix"}
]

[previewers]
prepend_previewers = [
    { mime = "text/plain", run = "nvim" }
]
